export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const AUTH_LOGIN_CHECK = 'AUTH_LOGIN_CHECK';

export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const GET_RESTAURANTS_START = 'GET_RESTAURANTS_START';
export const GET_RESTAURANTS_SUCCESS = 'GET_RESTAURANTS_SUCCESS';
export const GET_RESTAURANTS_FAIL = 'GET_RESTAURANTS_FAIL';

export const ARCHIVE_RESTAURANT_START = 'ARCHIVE_RESTAURANT_START';
export const ARCHIVE_RESTAURANT_SUCCESS = 'ARCHIVE_RESTAURANT_SUCCESS';
export const ARCHIVE_RESTAURANT_FAIL = 'ARCHIVE_RESTAURANT_FAIL';

export const ADD_RESTAURANT_START = 'ADD_RESTAURANT_START';
export const ADD_RESTAURANT_SUCCESS = 'ADD_RESTAURANT_SUCCESS';
export const ADD_RESTAURANT_FAIL = 'ADD_RESTAURANT_FAIL';

export const CHANGE_ACTIVE_RESTAURANT_START = 'CHANGE_ACTIVE_RESTAURANT_START';
export const CHANGE_ACTIVE_RESTAURANT_SUCCESS = 'CHANGE_ACTIVE_RESTAURANT_SUCCESS';
export const CHANGE_ACTIVE_RESTAURANT_FAIL = 'CHANGE_ACTIVE_RESTAURANT_FAIL';

export const GET_ACTIVE_RESTAURANT_START = 'GET_ACTIVE_RESTAURANT_START';
export const GET_ACTIVE_RESTAURANT_SUCCESS = 'GET_ACTIVE_RESTAURANT_SUCCESS';
export const GET_ACTIVE_RESTAURANT_FAIL = 'GET_ACTIVE_RESTAURANT_FAIL';

export const GET_USER_DATA_START = 'GET_USER_DATA_START';
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';
export const GET_USER_DATA_FAIL = 'GET_USER_DATA_FAIL';

export const GET_USER_START = 'GET_USER_START';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';

export const ADD_IMAGE_START = 'ADD_IMAGE_START';
export const ADD_IMAGE_SUCCESS = 'ADD_IMAGE_SUCCESS';
export const ADD_IMAGE_FAIL = 'ADD_IMAGE_FAIL';

export const GET_IMAGES_START = 'GET_IMAGES_START';
export const GET_IMAGES_SUCCESS = 'GET_IMAGES_SUCCESS';
export const GET_IMAGES_FAIL = 'GET_IMAGES_FAIL';

export const DELETE_IMAGE_START = 'DELETE_IMAGE_START';
export const DELETE_IMAGE_SUCCESS = 'DELETE_IMAGE_SUCCESS';
export const DELETE_IMAGE_FAIL = 'DELETE_IMAGE_FAIL';

export const ADD_ITEM_CATEGORY_START = 'ADD_ITEM_CATEGORY_START';
export const ADD_ITEM_CATEGORY_SUCCESS = 'ADD_ITEM_CATEGORY_SUCCESS';
export const ADD_ITEM_CATEGORY_FAIL = 'ADD_ITEM_CATEGORY_FAIL';

export const GET_ITEM_CATEGORIES_START = 'GET_ITEM_CATEGORIES_START';
export const GET_ITEM_CATEGORIES_SUCCESS = 'GET_ITEM_CATEGORIES_SUCCESS';
export const GET_ITEM_CATEGORIES_FAIL = 'GET_ITEM_CATEGORIES_FAIL';

export const UPDATE_ITEM_CATEGORY_START = 'UPDATE_ITEM_CATEGORY_START';
export const UPDATE_ITEM_CATEGORY_SUCCESS = 'UPDATE_ITEM_CATEGORY_SUCCESS';
export const UPDATE_ITEM_CATEGORY_FAIL = 'UPDATE_ITEM_CATEGORY_FAIL';

export const DELETE_ITEM_CATEGORY_START = 'DELETE_ITEM_CATEGORY_START';
export const DELETE_ITEM_CATEGORY_SUCCESS = 'DELETE_ITEM_CATEGORY_SUCCESS';
export const DELETE_ITEM_CATEGORY_FAIL = 'DELETE_ITEM_CATEGORY_FAIL';
